name: flutterquiz
description: A new Flutter application.

publish_to: "none"

version: 1.0.1+1

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  apple_sign_in_safety: ^0.0.6
  assets_audio_player: ^3.0.4+1
  cached_network_image: ^3.0.0
  cloud_firestore: ^4.0.3
  connectivity_plus: ^3.0.2
  cupertino_icons: ^1.0.3
  facebook_audience_network: ^1.0.0-nullsafety.0
  firebase_auth: ^4.1.0
  firebase_core: ^2.1.1
  firebase_messaging: ^14.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_exif_rotation: ^0.5.1
  flutter_html: ^3.0.0-alpha.1
  flutter_local_notifications: ^12.0.3
  flutter_localizations:
    sdk: flutter
  flutter_login_facebook: ^1.2.0
  flutter_svg: ^1.0.0
  google_fonts: ^3.0.1
  google_mobile_ads: ^2.2.0
  google_sign_in: ^5.1.0
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  http: ^0.13.3
#  unity_ads_plugin: ^0.3.5
  image_picker: ^0.8.0+1
  in_app_purchase: ^3.0.4
  internet_connection_checker:
  ios_insecure_screen_detector: ^0.0.2
  intl:
  intl_phone_field: ^3.1.0
  just_audio: ^0.9.12
  launch_review: ^3.0.1
  lottie: ^1.1.0
  octo_image: ^1.0.0+1
  #otp_autofill: ^1.1.0
  package_info_plus: ^3.0.1
  path_provider: ^2.0.2
  pin_code_fields: ^7.3.0
  scratcher: ^2.1.0
  screenshot: ^1.2.1
  share_plus: ^6.2.0
  shared_preferences: ^2.0.6
  sms_autofill: ^2.2.0
  url_launcher: ^6.0.12
  wakelock: ^0.6.1+2
  webview_flutter: ^3.0.0
  country_code_picker: ^2.0.2
  flutter_windowmanager: ^0.2.0
  encrypt:
  flutter_tex:
  upi_india:
  flutter_custom_tabs:
#  phonepe: ^0.0.1
#  phonepe_payment_sdk:



dev_dependencies:
  change_app_package_name: ^1.0.0
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/google_fonts/
    - assets/images/
    - assets/images/profile/

    - assets/images/emojis/
    - assets/images/coins/

    - assets/languages/
    - assets/animations/

    - assets/sounds/
    - assets/files/
